### ISSUE TITLE
[PRE REVIEW]: Effortless Bayesian Deep Learning in Julia through Laplace

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#101]
**Submitting author:** @pat-alt (<a href="http://orcid.org/0000-0003-4726-8613">Patrick Altmeyer</a>)
**Repository:** <a href="https://github.com/pat-alt/LaplaceRedux.jl" target ="_blank">https://github.com/pat-alt/LaplaceRedux.jl</a>
**Version:** 
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Mathieu Besançon

**Author instructions**

Thanks for submitting your paper to JCON @pat-alt. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @ranjanan.

@pat-alt if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 1121

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00101/jcon.00101/10.21105.jcon.00101.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00101/jcon.00101/10.21105.jcon.00101.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- doi.org/10.1038/s41597-020-0448-0 is OK

MISSING DOIs

- 10.2139/ssrn.195733 may be a valid DOI for title: Instrumental Variables Estimates of the Effect of Subsidized Training on the Quantiles of Trainee Earnings
- 10.1109/deeptest52559.2021.00007 may be a valid DOI for title: Machine Learning Model Drift Detection Via Weak Data Slices
- 10.3386/w20343 may be a valid DOI for title: Reference-Dependent Preferences: Evidence from Marathon Runners
- 10.1257/aer.99.1.486 may be a valid DOI for title: Indirect Effects of an Aid Program: How Do Cash Transfers Affect Ineligibles’ Consumption?
- 10.1017/cbo9780511618031.014 may be a valid DOI for title: “Coherent Arbitrariness”: Stable Demand Curves without Stable Preferences
- 10.1017/cbo9780511618031.015 may be a valid DOI for title: Tom Sawyer and the Construction of Value
- 10.1016/j.inffus.2019.12.012 may be a valid DOI for title: Explainable Artificial Intelligence (XAI): Concepts, Taxonomies, Opportunities and Challenges toward Responsible AI
- 10.7551/mitpress/3077.003.0044 may be a valid DOI for title: Deciding Advantageously before Knowing the Advantageous Strategy
- 10.1007/978-1-4419-9096-9 may be a valid DOI for title: Reproducing Kernel Hilbert Spaces in Probability and Statistics
- 10.3386/w3487 may be a valid DOI for title: The Federal Funds Rate and the Channels of Monetary Transnission
- 10.1016/j.techsoc.2021.101852 may be a valid DOI for title: Machine Learning, Knowledge Risk, and Principal-Agent Problems in Automated Trading
- 10.2139/ssrn.965818 may be a valid DOI for title: Identification of Peer Effects through Social Networks
- 10.2139/ssrn.3534495 may be a valid DOI for title: Peer Effects in Networks: A Survey
- 10.2307/2234554 may be a valid DOI for title: Nonlinear Dynamics, Chaos, and Instability: Statistical Theory and Economic Evidence
- 10.3386/w4509 may be a valid DOI for title: Minimum Wages and Employment: A Case Study of the Fast Food Industry in New Jersey and Pennsylvania
- 10.1109/sp.2017.49 may be a valid DOI for title: Towards Evaluating the Robustness of Neural Networks
- 10.3386/w14032 may be a valid DOI for title: Does Your Cohort Matter? Measuring Peer Effects in College Achievement
- 10.3982/ecta10168 may be a valid DOI for title: From Natural Variation to Optimal Policy? The Importance of Endogenous Peer Group Formation
- 10.2139/ssrn.4090707 may be a valid DOI for title: Explainable Artificial Intelligence: Interpreting Default Forecasting Models Based on Machine Learning
- 10.3386/w15617 may be a valid DOI for title: Adjustment Costs, Firm Responses, and Micro vs. Macro Labor Supply Elasticities: Evidence from Danish Tax Records
- 10.1214/18-aoas1222 may be a valid DOI for title: Variable Prioritization in Nonlinear Black Box Methods: A Genetic Association Case Study
- 10.1145/3514094.3534144 may be a valid DOI for title: Counterfactual Explanations for Prediction and Diagnosis in Xai
- 10.1080/01621459.1999.10473858 may be a valid DOI for title: Causal Effects in Nonexperimental Studies: Reevaluating the Evaluation of Training Programs
- 10.2139/ssrn.1596425 may be a valid DOI for title: The Persistent Effects of Peru’s Mining Mita
- 10.3233/ds-200028 may be a valid DOI for title: Reinforcement Learning for Personalization: A Systematic Literature Review
- 10.3390/app11167274 may be a valid DOI for title: A Framework and Benchmarking Study for Counterfactual Generating Methods on Tabular Data
- 10.1037/0022-3514.37.7.1097 may be a valid DOI for title: The Stability of Behavior: I. On Predicting Most of the People Much of the Time.
- 10.1086/497818 may be a valid DOI for title: Clean Evidence on Peer Effects
- 10.2139/ssrn.203194 may be a valid DOI for title: Cooperation and Punishment in Public Goods Experiments
- 10.1287/mnsc.2017.2908 may be a valid DOI for title: On the External Validity of Social Preference Games: A Systematic Lab-Field Study
- 10.1037/0022-3514.75.3.617 may be a valid DOI for title: Immune Neglect: A Source of Durability Bias in Affective Forecasting.
- 10.1037/e722842011-016 may be a valid DOI for title: The Uncertainty Effect: When a Risky Prospect Is Valued Less than Its Worst Possible Outcome
- 10.1007/978-3-030-42553-1_3 may be a valid DOI for title: Bayesian Neural Networks: An Introduction and Survey
- 10.3386/w11562 may be a valid DOI for title: The Incredible Volcker Disinflation
- 10.1920/wp.cem.2017.0817 may be a valid DOI for title: An Econometric Model of Network Formation with Degree Heterogeneity
- 10.1017/cbo9780511618031.006 may be a valid DOI for title: Economic Theory of Choice and the Preference Reversal Phenomenon
- 10.1086/717935 may be a valid DOI for title: Name Your Friends, but Only Five? The Importance of Censoring in Peer Effects Estimates Using Social Network Data
- 10.1109/icmla.2011.144 may be a valid DOI for title: Thompson Sampling for Dynamic Multi-Armed Bandits
- 10.1016/j.ins.2008.07.024 may be a valid DOI for title: Improving Artificial Neural Networks’ Performance in Seasonal Time Series Forecasting
- 10.1145/1273496.1273541 may be a valid DOI for title: A Bound on the Label Complexity of Agnostic Active Learning
- 10.1177/2053951720926558 may be a valid DOI for title: The Virtue of Simplicity: On Machine Learning Models in Algorithmic Trading
- 10.1509/jmkr.48.spl.s23 may be a valid DOI for title: Increasing Saving Behavior through Age-Progressed Renderings of the Future Self
- 10.1006/obhd.1996.0077 may be a valid DOI for title: The Evaluability Hypothesis: An Explanation for Preference Reversals between Joint and Separate Evaluations of Alternatives
- 10.1017/cbo9780511618031.033 may be a valid DOI for title: Music, Pandas, and Muggers: On the Affective Psychology of Value.
- 10.1002/jae.2426 may be a valid DOI for title: A Social Interactions Model with Endogenous Friendship Formation and Selectivity
- 10.21105/joss.00602 may be a valid DOI for title: Flux: Elegant Machine Learning with Julia
- 10.1257/aer.97.3.890 may be a valid DOI for title: Meeting Strangers and Friends of Friends: How Random Are Social Networks?
- 10.1126/science.1111709 may be a valid DOI for title: Failure to Detect Mismatches between Intention and Outcome in a Simple Decision Task
- 10.2139/ssrn.3043404 may be a valid DOI for title: Estimation of Peer Effects in Endogenous Social Networks: Control Function Approach
- 10.1198/1061860032148 may be a valid DOI for title: A Modified Principal Component Technique Based on the LASSO
- 10.1109/mci.2022.3155327 may be a valid DOI for title: Hands-on Bayesian Neural Networks–a Tutorial for Deep Learning Users
- 10.1017/cbo9781139175197.009 may be a valid DOI for title: Experimental Tests of the Endowment Effect and the Coase Theorem
- 10.1016/0749-5978(92)90015-y may be a valid DOI for title: Reference Points, Anchors, Norms, and Mixed Feelings
- 10.1145/3313831.3376219 may be a valid DOI for title: Interpreting Interpretability: Understanding Data Scientists’ Use of Interpretability Tools for Machine Learning
- 10.4314/ajst.v5i2.15330 may be a valid DOI for title: Seasonal Time Series Forecasting: A Comparative Study of ARIMA and ANN Models
- 10.1007/978-3-030-93842-0_6 may be a valid DOI for title: Exploring Explainable AI in the Financial Sector: Perspectives of Banks and Supervisory Authorities
- 10.1081/etc-120025891 may be a valid DOI for title: Best Spatial Two-Stage Least Squares Estimators for a Spatial Autoregressive Model with Autoregressive Disturbances
- 10.1177/0956797612450302 may be a valid DOI for title: The Financial Costs of Sadness
- 10.3386/w9736 may be a valid DOI for title: Neoclassical Theory versus Prospect Theory: Evidence from the Marketplace
- 10.3386/w7682 may be a valid DOI for title: The Power of Suggestion: Inertia in 401 (k) Participation and Savings Behavior
- 10.2307/2298123 may be a valid DOI for title: Identification of Endogenous Social Effects: The Reflection Problem
- 10.2139/ssrn.2523510 may be a valid DOI for title: Goals as Reference Points in Marathon Running: A Novel Test of Reference Dependence
- 10.20955/wp.2015.012 may be a valid DOI for title: FRED-MD: A Monthly Database for Macroeconomic Research
- 10.1007/s10618-013-0342-x may be a valid DOI for title: Visualizing Multi-Dimensional Decision Boundaries in 2D
- 10.1016/j.artint.2018.07.007 may be a valid DOI for title: Explanation in Artificial Intelligence: Insights from the Social Sciences
- 10.1037/0022-3514.54.4.687 may be a valid DOI for title: The Nature of Adolescent Competencies Predicted by Preschool Delay of Gratification.
- 10.1145/3287560.3287574 may be a valid DOI for title: Explaining Explanations in AI
- 10.1145/3351095.3372850 may be a valid DOI for title: Explaining Machine Learning Classifiers through Diverse Counterfactual Explanations
- 10.1109/cisda.2015.7208643 may be a valid DOI for title: Evaluating Model Drift in Machine Learning Algorithms
- 10.1016/s0167-7152(96)00140-x may be a valid DOI for title: Sparse Spatial Autoregressions
- 10.1145/3241036 may be a valid DOI for title: The Seven Tools of Causal Inference, with Reflections on Machine Learning
- 10.5860/choice.38-4002 may be a valid DOI for title: Economic Events, Ideas, and Policies: The 1960s and After
- 10.1016/j.jeconom.2014.08.008 may be a valid DOI for title: Estimating a Spatial Autoregressive Model with an Endogenous Spatial Weight Matrix
- 10.3386/w2966 may be a valid DOI for title: Does Monetary Policy Matter? A New Test in the Spirit of Friedman and Schwartz
- 10.1038/s42256-019-0048-x may be a valid DOI for title: Stop Explaining Black Box Machine Learning Models for High Stakes Decisions and Use Interpretable Models Instead
- 10.3386/w7469 may be a valid DOI for title: Peer Effects with Random Assignment: Results for Dartmouth Roommates
- 10.1080/01621459.2017.1395341 may be a valid DOI for title: Least Ambiguous Set-Valued Classifiers with Bounded Error Levels
- 10.1109/icdcsw.2011.20 may be a valid DOI for title: Finding a" Kneedle" in a Haystack: Detecting Knee Points in System Behavior
- 10.1086/209205 may be a valid DOI for title: Choice Based on Reasons: The Case of Attraction and Compromise Effects
- 10.21034/qr.1011 may be a valid DOI for title: Are Forecasting Models Usable for Policy Analysis?
- 10.1037/e301532005-001 may be a valid DOI for title: Who Accepts Savage’s Axiom?
- 10.1109/tmm.2014.2330697 may be a valid DOI for title: A Simple Method to Determine If a Music Information Retrieval System Is a “Horse”
- 10.1017/cbo9780511618031.039 may be a valid DOI for title: Libertarian Paternalism Is Not an Oxymoron
- 10.1016/0165-1765(81)90067-7 may be a valid DOI for title: Some Empirical Evidence on Dynamic Inconsistency
- 10.1086/380085 may be a valid DOI for title: Save More Tomorrow™: Using Behavioral Economics to Increase Employee Saving
- 10.1007/978-1-4613-2391-4_2 may be a valid DOI for title: The Framing of Decisions and the Psychology of Choice
- 10.1177/0956797610396225 may be a valid DOI for title: How Incidental Values from the Environment Affect Decisions about Money, Risk, and Delay
- 10.1145/3287560.3287566 may be a valid DOI for title: Actionable Recourse in Linear Classification
- 10.1037/0022-3514.79.1.66 may be a valid DOI for title: Egocentric Empathy Gaps between Owners and Buyers: Misperceptions of the Endowment Effect.
- 10.2139/ssrn.3589337 may be a valid DOI for title: Modeling Multivariate Time Series in Economics: From Auto-Regressions to Recurrent Neural Networks
- 10.2139/ssrn.3063289 may be a valid DOI for title: Counterfactual Explanations without Opening the Black Box: Automated Decisions and the GDPR
- 10.1007/bf00116900 may be a valid DOI for title: Learning in the Presence of Concept Drift and Hidden Contexts
- 10.1093/biostatistics/kxp008 may be a valid DOI for title: A Penalized Matrix Decomposition, with Applications to Sparse Principal Components and Canonical Correlation Analysis
- 10.1016/j.eswa.2007.12.020 may be a valid DOI for title: The Comparisons of Data Mining Techniques for the Predictive Accuracy of Probability of Default of Credit Card Clients
- 10.1016/s0925-2312(01)00702-0 may be a valid DOI for title: Time Series Forecasting Using a Hybrid ARIMA and Neural Network Model

INVALID DOIs

- None
```

**Comment by carstenbauer** [comment]
@whedon assign @ranjanan as editor

**Comment by whedon** [comment]
OK, the editor is @ranjanan

**Comment by pat-alt** [comment]
Just to flag that I've since added various updates to the package and will add those to the draft paper where necessary as soon as possible.

**Comment by ranjanan** [comment]
@pat-alt please let me know when you're satisfied with your draft and I'm happy to remove this label. I am also look for reviewers for this. If you've suggestions, ping me privately on Slack with names and I can reach out to them

**Comment by pat-alt** [comment]
@ranjanan sorry for the delay, have been caught up in work on two other submissions. I'm happy with the draft now. Please see [6f692bd](https://github.com/pat-alt/LaplaceRedux.jl/commit/6f692bd5808301eccb8fdc2db4dacd4a3af21bd2) for the up-to-date version. 

I have many further [improvements](https://github.com/pat-alt/LaplaceRedux.jl/issues) for the package in mind, but this will take more time (and hopefully community contributions 😄).

**Comment by pat-alt** [comment]
@whedon generate pdf

**Comment by pat-alt** [comment]
Also, as mentioned elsewhere, there is some https://github.com/JuliaCon/JuliaConSubmission.jl/issues/31 with listing captions. I have simply refrained from using captions for now, but this messes up the cross-references, so that definitely needs editing.

**Comment by pat-alt** [comment]
@ranjanan hope you're well!

I'm aware you're in the midst of planning JuliaCon 2023, but is there anything I can do to accelerate this process? Happy to openly ask for reviewers on discourse, slack and my socials if that's acceptable.

We currently have a group of TU Delft students working on this package full time for >2 months, so there have already been substantial updates. By the end of that it may well be worth turning this abstract into a full paper. Would that still be possible?

Please let me know if I can help in any way, would be great to see this move forward 😃

**Comment by matbesancon** [comment]
@whedon assign @matbesancon as editor

**Comment by matbesancon** [comment]
@pat-alt will reach out on Slack :)

**Comment by matbesancon** [comment]
Current status is on pause while authors refactor some parts

**Comment by pat-alt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
PDF failed to compile for issue #101 with the following error: 
```
 /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `initialize': No such file or directory @ rb_sysopen - 8bce03953c19685321221aa1/paper/src/paper.yml (Errno::ENOENT)
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `open'
	from /app/vendor/ruby-2.6.6/lib/ruby/2.6.0/psych.rb:577:in `load_file'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:125:in `load_yaml'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:66:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by pat-alt** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00101/jcon.00101/10.21105.jcon.00101.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00101/jcon.00101/10.21105.jcon.00101.pdf) :page_facing_up: :point_left:

**Comment by pat-alt** [comment]
Following discussions on Slack, I have now updated the paper. It is still just an extended abstract but now up-to-date. Thanks for your advice @matbesancon - this is now ready for review from my side.

Small note: since the package was originally presented in 2022, the header still states that year (happy to adjust that if necessary)

**Comment by pat-alt** [comment]
The package is now compatible with [CounterfactualExplanations.jl](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl) and it might be interesting to add another paragraph about this interplay. But I'm currently at exactly 2 pages, which I believe is the maximum length for extended abstracts?

**Comment by matbesancon** [comment]
@editorialbot generate pdf

**Comment by matbesancon** [comment]
> it might be interesting to add another paragraph about this interplay. But I'm currently at exactly 2 pages

yes indeed, we try to keep the extended abstract a summary of the package, as opposed to a proceeding which contains more explanation on the package, its usage, the methods underlying it

**Comment by pat-alt** [comment]
@matbesancon thought I'd check in on this. Anything I can do to help find a reviewer for this? I can think of a few collaborators at [Taija](https://www.taija.org/) but perhaps that's not ideal?

**Comment by matbesancon** [comment]
I'll drop you a DM

**Comment by matbesancon** [comment]
@editorialbot add @cpfiffer as reviewer

**Comment by cpfiffer** [comment]
I've gone through this and don't have any substantive notes -- what should I do now?
