### ISSUE TITLE
[PRE REVIEW]: JuliaCon submission

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#2]
**Submitting author:** @matbesancon (<a href="http://orcid.org/0000-0002-6284-3033">Mathieu Besançon</a>)
**Repository:** <a href="https://github.com/matbesancon/JuliaConSubmission.jl" target ="_blank">https://github.com/matbesancon/JuliaConSubmission.jl</a>
**Version:** v0.1.0
**Editor:** Pending
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JuliaCon @matbesancon. **Currently, there isn't an JuliaCon editor assigned** to your paper.

@matbesancon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #2 with the following error: 

 /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon/processor.rb:33:in `new'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon/processor.rb:33:in `set_paper'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `<main>'

**Comment by matbesancon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00002/jcon.00002/10.21105.jcon.00002.pdf)
