### ISSUE TITLE
[PRE REVIEW]: Test paper

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#3]
**Submitting author:** @arfon (<a href="http://orcid.org/0000-0002-3957-2474">Arfon Smith</a>)
**Repository:** <a href="https://github.com/arfon/JuliaConSubmission.jl" target ="_blank">https://github.com/arfon/JuliaConSubmission.jl</a>
**Version:** v1.0.0
**Editor:** @arfon
**Reviewers:** @arfon

**Author instructions**

Thanks for submitting your paper to JuliaCon @arfon. The JuliaCon editor @arfon, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@arfon if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JuliaCon and may be suitable for this submission.

**Editor instructions**

The JuliaCon submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @arfon it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@arfon) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3 with the following error: 

 /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon.rb:115:in `check_fields': Paper YAML header is missing expected fields: date (RuntimeError)
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon.rb:80:in `initialize'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon/processor.rb:33:in `new'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/lib/whedon/processor.rb:33:in `set_paper'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.5.0/bundler/gems/whedon-0a2cd51df451/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.5.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00003/jcon.00003/10.21105.jcon.00003.pdf)

**Comment by arfon** [comment]
@whedon add @arfon as reviewer

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon commands

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to accept the paper and deposit with Crossref
@whedon accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by arfon** [comment]
@whedon add @arfon as reviewer

**Comment by arfon** [comment]
@whedon add @arfon as reviewer

**Comment by whedon** [comment]
OK, @arfon is now a reviewer

**Comment by arfon** [comment]
@whedon assign @arfon as reviewer

**Comment by whedon** [comment]
OK, the reviewer is @arfon

**Comment by arfon** [comment]
@whedon start review

**Comment by arfon** [comment]
@whedon start review

**Comment by whedon** [comment]
OK, I've started the review over in https://github.com/JuliaCon/proceedings-review/issues/4. Feel free to close this issue now!

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
PDF failed to compile for issue #3 with the following error: 

 Can't find any papers to compile :-(

**Comment by arfon** [comment]
@whedon check references

**Comment by whedon** [comment]
```
Attempting to check references...
```

**Comment by whedon** [comment]
```Reference check summary:

OK DOIs

- 10.1287/opre.38.5.911 is OK

MISSING DOIs

- https://doi.org/10.1137/141000671 may be missing for title: Julia: A fresh approach to numerical computing

INVALID DOIs

- None
```

**Comment by arfon** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment]
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00003/jcon.00003/10.21105.jcon.00003.pdf)

**Comment by arfon** [comment]
@whedon accept

**Comment by whedon** [comment]
I can't accept a paper that hasn't been reviewed!
