### ISSUE TITLE
[PRE REVIEW]: Testing the Julia SciML ecosystem through Physics-Informed Machine Learning applied to wildfire propagation

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#81]
**Submitting author:** @francescocalisto (<a href="http://orcid.org/0000-0003-4026-7239">Francesco Calisto</a>)
**Repository:** <a href="https://github.com/MachineLearningJournalClub/MLJC-UniTo-ProjectX-2020-public.git" target ="_blank">https://github.com/MachineLearningJournalClub/MLJC-UniTo-ProjectX-2020-public.git</a>
**Version:** 
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @francescocalisto. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @carstenbauer.

@francescocalisto if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
PDF failed to compile for issue #81 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Simone Azeglio, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 4551

**Comment by whedon** [comment]
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5065/1DFH-6P97 is OK
- 10.1007/s10584-014-1183-3 is OK
- 10.7930/nca4.2018 is OK
- 10.1126/science.1259100 is OK
- 10.3390/rs10121950 is OK
- 10.5194/gmd-4-591-2011 is OK
- 10.1016/0893-6080(92)90012-8 is OK
- 10.1287/ijoc.2014.0623 is OK

MISSING DOIs

- 10.21203/rs.3.rs-55125/v1 may be a valid DOI for title: Universal differential equations for scientific machine learning
- 10.1016/j.ymeth.2019.04.008 may be a valid DOI for title: Deep learning in bioinformatics: Introduction, application, and perspective in the big data era
- 10.1016/j.jcp.2018.10.045 may be a valid DOI for title: Physics-informed neural networks: A deep learning framework for solving forward and inverse problems involving nonlinear partial differential equations
- 10.1016/j.tcs.2011.01.039 may be a valid DOI for title: The directed Hausdorff distance between imprecise point sets

INVALID DOIs

- None
```

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=1.26 s (205.2 files/s, 134088.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Fortran 77                     154           1868          20046          22372
Julia                           37           1552           1618           4472
TeX                              8            315            177           2618
TOML                             4            455              2           2138
Jupyter Notebook                19              0         107222           1363
C                                9            169            432            947
Markdown                        15            257              0            528
make                             4             55             40            149
C++                              2             29             46             71
C Shell                          1             13              0             49
Prolog                           1              1              0             44
OCaml                            1              0              0             42
Ruby                             1              7              3             37
YAML                             1              1              0             32
C/C++ Header                     2              4             12             22
-------------------------------------------------------------------------------
SUM:                           259           4726         129598          34884
-------------------------------------------------------------------------------


Statistical information for the repository '26666763464e5ce00b4b95a7' was
gathered on 2021/09/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Francesco Calisto                1            47              0            2.16
Martina Scauda                   2          1929            197           97.84

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Francesco Calisto            47          100.0          0.0                6.38
Martina Scauda             1732           89.8          0.0               29.97
```

**Comment by francescocalisto** [comment]
matbesancon might be an available reviewer, according to the list

**Comment by carstenbauer** [comment]
@whedon assign @carstenbauer as editor

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00081/jcon.00081/10.21105.jcon.00081.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00081/jcon.00081/10.21105.jcon.00081.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment]
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by carstenbauer** [comment]
@whedon add @sloede as reviewer

**Comment by whedon** [comment]
OK, @sloede is now a reviewer

**Comment by carstenbauer** [comment]
@francescocalisto While I'm already in the process of looking out for reviewers, can you suggest a few reviewers without conflict of interest from the scientific machine learning community? Could also be someone from a different open source community, e.g. from the Python community.

**Comment by ChrisRackauckas** [comment]
Wasn't this published in the AAAI-MLPS 2021 archival proceedings already? https://sites.google.com/view/aaai-mlps/proceedings?authuser=0

**Comment by francescocalisto** [comment]
I didn't know, sorry! I agree on that. Then I think we can close the issue. Thank you.

**Comment by vchuravy** [comment]
@whedon withdraw
