### ISSUE TITLE
[PRE REVIEW]: LazySets.jl: Scalable Symbolic-Numeric Set Computations

### ISSUE THREAD

**Issue by whedon** [JuliaCon/proceedings-review#86]
**Submitting author:** @mforets (<a href="http://orcid.org/0000-0002-9831-7801">Marcelo Forets</a>)
**Repository:** <a href="https://github.com/JuliaReach/LazySets-JuliaCon21" target ="_blank">https://github.com/JuliaReach/LazySets-JuliaCon21</a>
**Version:** 
**Editor:** Pending
**Reviewer:** Pending
**Managing EiC:** Valentin Churavy

**Author instructions**

Thanks for submitting your paper to JCON @mforets. **Currently, there isn't an JCON editor assigned** to your paper.

The author's suggestion for the handling editor is @matbesancon.

@mforets if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/jcon-reviewers) have already agreed to review for JCON and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JCON submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment]
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment]
Failed to discover a `Statement of need` section in paper

**Comment by whedon** [comment]
Wordcount for `paper.tex` is 68

**Comment by whedon** [comment]
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.03 s (743.1 files/s, 152701.3 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TeX                             18            514            305           3272
Julia                            1             80             70            185
Ruby                             1              8              4             45
YAML                             1              0              0             22
Markdown                         1              7              0              9
-------------------------------------------------------------------------------
SUM:                            22            609            379           3533
-------------------------------------------------------------------------------


Statistical information for the repository '6d280d04702fece8bfe741ca' was
gathered on 2021/09/30.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
mforets                          1            57              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
mforets                      57          100.0          0.0                7.02
```

**Comment by whedon** [comment]
Failed to discover a valid open source license.

**Comment by whedon** [comment]
Checking the BibTeX entries failed with the following error: 

 Failed to parse BibTeX on value "@" (AT) [#<BibTeX::Bibliography data=[1]>, "@", #<BibTeX::Entry >, {:author=>["Luca Geretti and Julien Alexandre Dit Sandretto and Matthias Althoff and Luis Benet and Alexandre Chapoutot and Xin Chen and Pieter Collins and Marcelo Forets and Daniel Freire and Fabian Immler and Niklas Kochdumper and David P. Sanders and Christian Schilling"], :title=>["{ARCH-COMP20} Category Report: Continuous and Hybrid Systems with Nonlinear Dynamics"], :booktitle=>["{ARCH}"], :series=>["EPiC Series in Computing"], :volume=>["74"], :pages=>["49--75"], :publisher=>["EasyChair"], :year=>["2020"]}, ","]

**Comment by whedon** [comment]
PDF failed to compile for issue #86 with the following error: 
```
 /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:72:in `block in build_affiliation_string': Problem with affiliations for Marcelo Forets, perhaps the affiliations index need quoting? (RuntimeError)
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:71:in `build_affiliation_string'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/author.rb:17:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:205:in `block in parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `each'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:202:in `parse_authors'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon.rb:93:in `initialize'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `new'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/lib/whedon/processor.rb:38:in `set_paper'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:58:in `prepare'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.6.0/bundler/gems/whedon-c5c16aedb3d6/bin/whedon:131:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.6.0/bin/whedon:23:in `<main>'

```

**Comment by mforets** [comment]
@whedon generate pdf

**Comment by whedon** [comment]
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/JuliaCon/proceedings-papers/jcon.00086/jcon.00086/10.21105.jcon.00086.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/JuliaCon/proceedings-papers/blob/jcon.00086/jcon.00086/10.21105.jcon.00086.pdf) :page_facing_up: :point_left:

**Comment by mforets** [comment]
> @mforets if you have any suggestions for potential reviewers then please mention them here

Here is a list of reviewer suggestions (please note that I haven't contacted any of them directly). The github handle is in parentheses.

- David P. Sanders (dpsanders)
- Luis Benet (lbenet)
- Benoit Legat (blegat)
- Christopher Rackauckas (chrisrackauckas)
- Júlio Hoffimann (juliohm)
- Chelsea Sidrane (chelseas)

**Comment by ChrisRackauckas** [comment]
Too busy right now 😅
